/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 old_pc.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/old_pc.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pc.geometry} material={nodes.pc.material} />
    </group>
  )
}

useGLTF.preload('/old_pc.gltf')
