/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Coach(props) {

  const { nodes, materials } = useGLTF('/models/furniture/coach.gltf')
  return (
      <group {...props} dispose={null}>
        <mesh geometry={nodes.cylinder.geometry} material={nodes.cylinder.material} receiveShadow />
        <mesh geometry={nodes.cylinder_1.geometry} material={nodes.cylinder_1.material} receiveShadow />
        <mesh geometry={nodes.cylinder_2.geometry} material={nodes.cylinder_2.material} receiveShadow />
        <mesh geometry={nodes.cylinder_3.geometry} material={nodes.cylinder_3.material} receiveShadow />
        <mesh geometry={nodes.cube.geometry} material={nodes.cube.material} receiveShadow />
        <mesh geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} position={[0, 0.63, -0.38]} rotation={[-0.13, 0, 0]} receiveShadow />
        <mesh geometry={nodes.cylinder_4.geometry} material={nodes.cylinder_4.material} receiveShadow />
        <mesh geometry={nodes.cylinder_5.geometry} material={nodes.cylinder_5.material} receiveShadow />
        <mesh geometry={nodes.cube_2.geometry} material={nodes.cube_2.material} receiveShadow />
      </group>
  )
}

useGLTF.preload('./models/furniture/coach.gltf')
